
source 'https://github.com/RonnieJia/RJSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

platform :ios, '9.0'

target 'RJLoginMoudle_Example' do
  pod 'RJLoginMoudle', :path => '../'
  
#  pod 'RJNetworking', '~>0.1.2'

  target 'RJLoginMoudle_Tests' do
    inherit! :search_paths

    
  end
end
